/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iphone-12-pro-05dfc991665e45c68c8b7062136c0c6e
title: iPhone 12 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/iphone.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 10]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
            <mesh geometry={nodes.Camera1_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera1_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera1_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera1_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera1_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera1_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Flash_Flash2_0.geometry} material={materials.Flash2} />
            <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
            <mesh geometry={nodes.LiDar_LiDar__0.geometry} material={materials.LiDar} />
            <mesh geometry={nodes.FrontCamera_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.FrontCamera_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.FrontCamera_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.FrontMic_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
            <mesh geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.FrontCamera001_bezel001_0.geometry} material={materials['bezel.001']} />
            <mesh geometry={nodes.Bezel_bezel_0.geometry} material={materials.bezel} />
            <mesh geometry={nodes.Camera3_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera3_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera3_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera3_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera3_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera3_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Camera2_PacificBlue_0.geometry} material={materials.PacificBlue} />
            <mesh geometry={nodes.Camera2_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
            <mesh geometry={nodes.Camera2_FrontCamera_0.geometry} material={materials.FrontCamera} />
            <mesh geometry={nodes.Camera2_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Camera2_Cameralens_0.geometry} material={materials.Cameralens} />
            <mesh geometry={nodes.Camera2_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Screen_Wallpaper_0.geometry} material={materials.Wallpaper} />
            <mesh geometry={nodes.Apple_Logo_Logo_0.geometry} material={materials.Logo} />
            <mesh geometry={nodes.CameraModule001_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.iPhone12_Pro_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.VolumeButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.PowerButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.Port_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.Port_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.SimTray_Blackmatte_0.geometry} material={materials.Blackmatte} />
            <mesh geometry={nodes.SimTray_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.MuteButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry} material={materials.BodyFrame} />
            <mesh geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
            <mesh geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
            <mesh geometry={nodes.iPhone__12_Pro_Antenna_0.geometry} material={materials.Antenna} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
